{
 "title": "HTTP",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RP24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_total[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статусы ответов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_total{status=\"2xx\"}[24h])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "floor(sum(increase(http_requests_total{status=\"3xx\"}[24h])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "floor(sum(increase(http_requests_total{status=\"4xx\"}[24h])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "floor(sum(increase(http_requests_total{status=\"5xx\"}[24h])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Статусы ответов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_total{status='2xx'}[1m])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "floor(sum(increase(http_requests_total{status='3xx'}[1m])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "floor(sum(increase(http_requests_total{status='4xx'}[1m])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "floor(sum(increase(http_requests_total{status='5xx'}[1m])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Время выполнения запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_highr_seconds_bucket[10m])) by (le)) * 1000",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_highr_seconds_bucket[10m])) by (le)) * 1000",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_highr_seconds_bucket[10m])) by (le)) * 1000",
     "legendFormat": "75%"
    }
   ]
  }
 ]
}