global:
    scrape_interval: 15s
    external_labels:
        monitor: 'codelab-monitor'

scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 30s
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'fastapi'
      scrape_interval: 30s
      static_configs:
          - targets: ['backend:8080']
