"""empty message

Revision ID: abdfaec4d01f
Revises: 
Create Date: 2025-04-28 12:12:09.326433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdfaec4d01f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create extension if not exists "uuid-ossp";')
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('interests', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('age_preferences', sa.Integer(), nullable=False),
    sa.Column('gender_preferences', sa.String(), nullable=False),
    sa.Column('interests_preferences', sa.String(), nullable=False),
    sa.Column('city_preferences', sa.String(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('referal_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['referal_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('user_interactions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('requester_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('responser_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['requester_telegram_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['responser_telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ratings',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ratings')
    op.drop_table('user_interactions')
    op.drop_table('users')
    # ### end Alembic commands ###
